ARG FROM_IMAGE_NAME=Cambricon_TensorFlow_Image:Image_tag

FROM ${FROM_IMAGE_NAME}

COPY ./tensorflow_modelzoo /home/tensorflow_modelzoo

WORKDIR /home/tensorflow_modelzoo/tensorflow/built-in/NaturalLanguageProcessing/google_bert

RUN cd ../../../../tools/record_time && pip install .
