ARG FROM_IMAGE_NAME=Cambricon_TensorFlow_Image:Image_tag

FROM ${FROM_IMAGE_NAME}

COPY ./tensorflow_modelzoo /home/tensorflow_modelzoo

WORKDIR /home/tensorflow_modelzoo/tensorflow2/built-in/TTS/LPCNet/

RUN apt-get update && \
 apt-get install -y autoconf automake libtool sox ffmpeg && \
 cd ../../../../tools/record_time && pip install . \
 && cd - && cd models && ./autogen.sh && ./configure && make 
 
